### ISSUE TITLE
zipped tarballs get very large after encrypting stream

### ISSUE THREAD

**Issue by timothyjlaurent** [marcobellaccini/pyAesCrypt#14]
I have tarballs that are about 81M but grow to 2.8G when encrypted with pyAESCrypt `encryptStream`.

What could be happening here?

**Comment by marcobellaccini** [comment]
Hi,
*pyAesCrypt* encrypted output is about the same size of the plaintext.
Maybe there's something wrong with your code: can you paste it here?

Moreover, as reported in the [README](https://github.com/marcobellaccini/pyAesCrypt/blob/master/README.rst), the he most straightforward way to use *pyAesCrypt* is by calling the **encryptFile**/**decryptFile** functions.
If you can, please use those instead of working with streams.

**Comment by marcobellaccini** [comment]
This issue seems stale.

I'm closing it: in case you still need help, you can open another issue.
