### ISSUE TITLE
pyAesCrypt.encryptStream(...) stucks when used inside a thread

### ISSUE THREAD

**Issue by hash3liZer** [marcobellaccini/pyAesCrypt#33]
Hi, I've been trying to encrypt a string using this. The function works fine when called from `python interpreter` or used in the **main thread**.  However, the following doesn't work: when it is used inside a thread:
```python
import io
import threading
import pyAesCrypt

def caller():
    toencrypt = io.BytesIO(b"Hello World")
    encrypted = io.BytesIO()

    pyAesCrypt.encryptStream(toencrypt, encrypted, "pass1122", 64*1024)   # Stuck here
    print(encrypted.getvalue())

def main():
    t  = threading.Thread(target=caller)
    t.daemon = True
    t.start()

    while True:
        pass 

if __name__ == "__main__":
    main()
```

**Comment by marcobellaccini** [comment]
Hi,
your issue is unrelated to _pyAesCrypt_: it's about threading in Python.
What you're experiencing it's just nominal threading behavior in CPython:

> In CPython, due to the Global Interpreter Lock, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation).

In other words, that:
`while True:`
`        pass `

is preventing _caller()_ from running.

You should try with _time.sleep()_ instead of  _pass_.
As an alternative, you can try to use a different parallel computing module (e.g. [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing)).

Please check [threading documentation](https://docs.python.org/3/library/threading.html) for more information.

Cheers

Marco
